### ISSUE TITLE
Stream / Buffer VideoView for smooth seekBar experience..

### ISSUE THREAD

**Issue by ab5593** [maiwenchang/ArtPlayer#13]
i am looking for how to **stream / buffer video** in videoView so that the video when skipped using `onStopTrackingTouch`  it doesnt stop.

 My onStopTrackingTouch method is as below 

    @Override
    public void onStopTrackingTouch(SeekBar seekBar) {
        Log.i(TAG, "bottomProgress onStopTrackingTouch [" + this.hashCode() + "] ");
        MediaPlayerManager.instance().startProgressTimer();
        ViewParent vpup = getParent();
        while (vpup != null) {
            vpup.requestDisallowInterceptTouchEvent(false);
            vpup = vpup.getParent();
        }
        if (MediaPlayerManager.instance().getPlayerState() != MediaPlayerManager.PlayerState.PLAYING &&
                MediaPlayerManager.instance().getPlayerState() != MediaPlayerManager.PlayerState.PAUSED)
            return;
        long time = (long) (seekBar.getProgress() * 1.00 / 100 * MediaPlayerManager.instance().getDuration());
        MediaPlayerManager.instance().seekTo(time);
        Log.i(TAG, "seekTo " + time + " [" + this.hashCode() + "] ");
    }

**Comment by maiwenchang** [comment]
what do you mean it doesn`t stop?
