### ISSUE TITLE
使用Https网络播放必须要加载完才能开始播放吗？

### ISSUE THREAD

**Issue by MikeVoy** [maiwenchang/ArtPlayer#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeVoy** [comment]
必须要缓存完整个视频才开始播放

**Comment by maiwenchang** [comment]
> 必须要缓存完整个视频才开始播放
不用的呀，URL发过来我试一下

**Comment by MikeVoy** [comment]
https://develop.atcc.fun/artworks/video/upload/video15530650836423.mp4，这是一个我自己上传了4秒左右的60帧视频，给我的观感就是全部加载完才开始播放的，而且之前用您demo 的视频链接是没有问题的

**Comment by maiwenchang** [comment]
你的连接打不开哦，现在还有这个疑惑吗？没有的话我关闭了
