### ISSUE TITLE
显示缓冲进度条问题

### ISSUE THREAD

**Issue by fukaimei** [maiwenchang/ArtPlayer#21]
你好，可不可加上播放过程中由于网速原因出现界面停止时显示缓冲进度条来提示用户的功能？

**Comment by maiwenchang** [comment]
这是个好建议，但是最近太忙没空做新功能，你有空可以加一下，欢迎随时pr，播放提示等等不是核心功能，完全可以自行扩展噢

**Comment by shuhao1022** [comment]
为什么拖动进度条不能快进呢？

**Comment by maiwenchang** [comment]
> 为什么拖动进度条不能快进呢？

可以快进的，你可以参考demo
