### ISSUE TITLE
旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏

### ISSUE THREAD

**Issue by shuhao1022** [maiwenchang/ArtPlayer#23]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maiwenchang** [comment]
请把你的代码发出来看一下

**Comment by shuhao1022** [comment]
进度条问题已经没问题了，你的demo报这个错，导致黑屏，因为退出全屏方法走了两次发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 15:59收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)看下你的代码

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
红色代码放进判断里应该就没问题，这是你的demo发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 15:59收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)看下你的代码

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
简单来说就是，点击返回走了一次退出全屏，屏幕回正又走了一次退出全屏方法发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 15:59收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)看下你的代码

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
在你源码里修改了，问题已解决，需要您这边更新到github上发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 15:59收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)看下你的代码

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
看到回复下，谢谢，因为我这边要改的话需要重新设置Orientationchangelistener发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 15:59收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)看下你的代码

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BILBUJJLG7H7PR6VFM3QB7YGDA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DEHTY#issuecomment-516309967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by maiwenchang** [comment]
没看到您说的红色代码，您可以fork这个项目，修改代码然后发起一个PR，如果合理的话，会合并进这个项目。

**Comment by shuhao1022** [comment]
我解决了黑屏问题，但是videoview下方的布局(暂停按钮，进度条)被隐藏了，所以您有时间的话复现一下。复现步骤，你demo主界面播放视频，然后旋转屏幕，然后按返回，手机拿正发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 17:30收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)没看到您说的红色代码，您可以fork这个项目，修改代码然后发起一个PR，如果合理的话，会合并进这个项目。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BIPLSG64VS72FZY5CQLQCAC4BA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DMGNA#issuecomment-516342580",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BIPLSG64VS72FZY5CQLQCAC4BA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DMGNA#issuecomment-516342580",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
OrientationChangeListener类 

@Override
    public void onOrientationPortrait(VideoView videoView) {
        //竖屏
        VideoView parentVideoView = videoView.getParentVideoView();
        if (parentVideoView != null) {
            parentVideoView.setControlPanel(videoView.getControlPanel());
        }
        videoView.exitFullscreen();
    }


把 videoView.exitFullscreen();放进上面判断，可以解决黑屏，当时下面的进度条和暂停按钮被隐藏了，您有时间可以看一哈，

**Comment by maiwenchang** [comment]
> OrientationChangeListener类
> 
> @override
> public void onOrientationPortrait(VideoView videoView) {
> //竖屏
> VideoView parentVideoView = videoView.getParentVideoView();
> if (parentVideoView != null) {
> parentVideoView.setControlPanel(videoView.getControlPanel());
> }
> videoView.exitFullscreen();
> }
> 
> 把 videoView.exitFullscreen();放进上面判断，可以解决黑屏，当时下面的进度条和暂停按钮被隐藏了，您有时间可以看一哈，

应该不是这么改的，我回去看一下，这种情况不应该调用这个方法。btw，这个方法本身应该没问题。

**Comment by shuhao1022** [comment]
对的，因为点那个放大按钮全屏后，再点返回，就不会调这里，显示也是正常的！所以我没改，还是大佬您自己看一下，挺喜欢你写的这个发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月30日 18:29收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)
OrientationChangeListener类
@override
public void onOrientationPortrait(VideoView videoView) {
//竖屏
VideoView parentVideoView = videoView.getParentVideoView();
if (parentVideoView != null) {
parentVideoView.setControlPanel(videoView.getControlPanel());
}
videoView.exitFullscreen();
}
把 videoView.exitFullscreen();放进上面判断，可以解决黑屏，当时下面的进度条和暂停按钮被隐藏了，您有时间可以看一哈，

应该不是这么改的，我回去看一下，这种情况不应该调用这个方法。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BIK2HANWBAFESA72UUTQCAJZNA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DRBHY#issuecomment-516362399",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BIK2HANWBAFESA72UUTQCAJZNA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3DRBHY#issuecomment-516362399",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
可以获取视频停止播放时候的进度吗，然后下次播放同一个视频可以续播？

**Comment by maiwenchang** [comment]
> 可以获取视频停止播放时候的进度吗，然后下次播放同一个视频可以续播？

可以，你可以在activity的onDestory里，通过MediaPlayerManager.getMediaPlayer().getCurrentPosition()先获取到当前播放的进度，保存起来，再去停止视频，下次就可以通过seekTo()方法续播了。

**Comment by shuhao1022** [comment]
谢谢回复，因为最近做视频项目，非常感谢发自我的iPhone------------------ 原始邮件 ------------------发件人: maiwenchang  <notifications@github.com>发送时间: 2019年7月31日 08:48收件人: maiwenchang/ArtPlayer <ArtPlayer@noreply.github.com>抄送: shuhao1022 <17322271022@163.com>, State change <state_change@noreply.github.com>主题: 回复：[maiwenchang/ArtPlayer] 旋转屏幕后进入全屏，点击左上角返回按钮或者手机自带返回键，videoview黑屏 (#23)
可以获取视频停止播放时候的进度吗，然后下次播放同一个视频可以续播？

可以，你可以在activity的onDestory里，通过MediaPlayerManager.getMediaPlayer().getCurrentPosition()先获取到当前播放的进度，保存起来，再去停止视频，下次就可以通过seekTo()方法续播了。

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BIL55EJJOMM2QUHGAXLQCDOOLA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3FXCPI#issuecomment-516649277",
"url": "https://github.com/maiwenchang/ArtPlayer/issues/23?email_source=notifications\u0026email_token=AMB2BIL55EJJOMM2QUHGAXLQCDOOLA5CNFSM4IHZDRZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3FXCPI#issuecomment-516649277",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuhao1022** [comment]
protected void onDestroy() {
        super.onDestroy();
        long currentPosition = MediaPlayerManager.instance().getMediaPlayer().getCurrentPosition();
        SharedPreferenceUtil.putLong("time",currentPosition);
        MediaPlayerManager.instance().releasePlayerAndView(this);
    }

 MediaPlayerManager.instance().releasePlayerAndView(this);
        MediaPlayerManager.instance().setMediaPlayer(new IjkPlayer());

        controlPanel = new ControlPanel(this);
        videoView.setControlPanel(controlPanel);
        //optional: set title
        TextView tvTitle = controlPanel.findViewById(R.id.tvTitle);
        tvTitle.setText("西虹市首富 百变首富预告");
        //required: set url
        videoView.setUp("http://vfx.mtime.cn/Video/2018/07/06/mp4/180706094003288023.mp4");
//        videoView.start();
        //optional: set cover
        Glide.with(this)
                .load("http://img5.mtime.cn/mg/2018/07/06/093947.51483272.jpg")
                .into((ImageView) controlPanel.findViewById(R.id.video_cover));
        long time = SharedPreferenceUtil.getLong("time", 0);
        if (time!=0){
            MediaPlayerManager.instance().getMediaPlayer().seekTo(time);
            videoView.start();
        }

time值也获取到了，但是它还是从0开始播放-0-

**Comment by maiwenchang** [comment]
> protected void onDestroy() {
> super.onDestroy();
> long currentPosition = MediaPlayerManager.instance().getMediaPlayer().getCurrentPosition();
> SharedPreferenceUtil.putLong("time",currentPosition);
> MediaPlayerManager.instance().releasePlayerAndView(this);
> }
> 
> MediaPlayerManager.instance().releasePlayerAndView(this);
> MediaPlayerManager.instance().setMediaPlayer(new IjkPlayer());
> 
> ```
>     controlPanel = new ControlPanel(this);
>     videoView.setControlPanel(controlPanel);
>     //optional: set title
>     TextView tvTitle = controlPanel.findViewById(R.id.tvTitle);
>     tvTitle.setText("西虹市首富 百变首富预告");
>     //required: set url
>     videoView.setUp("http://vfx.mtime.cn/Video/2018/07/06/mp4/180706094003288023.mp4");
> ```
> 
> // videoView.start();
> //optional: set cover
> Glide.with(this)
> .load("http://img5.mtime.cn/mg/2018/07/06/093947.51483272.jpg")
> .into((ImageView) controlPanel.findViewById(R.id.video_cover));
> long time = SharedPreferenceUtil.getLong("time", 0);
> if (time!=0){
> MediaPlayerManager.instance().getMediaPlayer().seekTo(time);
> videoView.start();
> }
> 
> time值也获取到了，但是它还是从0开始播放-0-

我猜应该要先start(),再seekTo();

**Comment by shuhao1022** [comment]
按你说的做了，用的MediaPlayerManager.instance().seekTo(time)，也进去
public void seekTo(long time) {
        mediaPlayer.seekTo(time);
    }
了，但是还是从头开始放的 ，不知道是不是start的问题

**Comment by maiwenchang** [comment]
已修复
