### ISSUE TITLE
How i access the exoplayer?

### ISSUE THREAD

**Issue by bawaviki** [maiwenchang/ArtPlayer#27]
I want to access the exo-player use in art-exo class for PlayerNotificationManager on exoplayer for background play .How i access or set  PlayerNotificationManager on exoplayer i also try to add a getter method in exoplayer class.

**Comment by maiwenchang** [comment]
1.`implementation "org.salient.artvideoplayer:artplayer-exo:0.7.0"`
2.`MediaPlayerManager.instance().setMediaPlayer(new ExoPlayer(this));`
