### ISSUE TITLE
Online video can not be played when complied with sdk 28 and 29

### ISSUE THREAD

**Issue by NanyangTaiji** [maiwenchang/ArtPlayer#30]
Still using exoplayer 2.8.4. The current version is already 2.10.4. Exoplayer went through a dramatic change in 2.10.1.

**Comment by maiwenchang** [comment]
I  would make an update for exoplayer these days, thanks for reminding.

**Comment by maiwenchang** [comment]
Exoplayer already updated to 2.11.1
