### ISSUE TITLE
我想问一下如何监听视频的播放进度

### ISSUE THREAD

**Issue by RenYanLin** [maiwenchang/ArtPlayer#35]
看源码也没找到相关的监听事件，有点懵，小白求救

**Comment by maiwenchang** [comment]
`AbsControlPanel.onProgressUpdate()`进度会回调到这里。
在`MediaPlayerManager `的最后可以看到进度的更新方式。

**Comment by RenYanLin** [comment]
感谢，我自定义了一个ControlPlanel，监听了一下各个的播放状态这个样子来控制的
