### ISSUE TITLE
请问全屏按钮能不能去掉？怎么去掉？

### ISSUE THREAD

**Issue by QY-WindRises** [maiwenchang/ArtPlayer#36]
MediaPlayerManager.instance ().clearFullscreenLayout ( VideoPlaybackActivity.this );
这一句是不是去掉全屏？但好像不顶用。

**Comment by maiwenchang** [comment]
这个涉及到自定义UI，你可以实现自己的UI，想要什么样都可以

**Comment by QY-WindRises** [comment]
> 这个涉及到自定义UI，你可以实现自己的UI，想要什么样都可以

谢谢
