### ISSUE TITLE
播放会有卡顿现象，使用exo内核

### ISSUE THREAD

**Issue by AlairEileen** [maiwenchang/ArtPlayer#37]
**videocover**
videocover应该是没有绑定到视图吧，况且一般imageview都用glide绑定，所以默认controlpanel可以吧imageview设为开放，这样比较容易绑定了

**卡顿现象常有，exo原生并不卡顿**
粗略的看了下内部，貌似是没有接口来调整缓存等等的

**Comment by maiwenchang** [comment]
对于封面的建议，controlpanel是一个FrameLayout，所以videocover可以通过findViewById的方式找到，`controlPanel.findViewById(R.id.video_cover)`，项目的MainActivity里有set cover的例子。

如果有卡顿现象，请发送一个连接我试一下，如果想调整缓存，我这边看一下怎么提供一个接口

**Comment by maiwenchang** [comment]
现在在重构Kotlin版本，会暴露播放器内核，可以自行调整缓存策略

**Comment by AlairEileen** [comment]
谢谢您的解答，虽然我能力还是很有限，不过我那段时间已经解决了。如果又kotlin版本我还会继续支持，如果有什么需要帮助的，我也可以尽微薄之力，虽然写Android sdk不是很熟，但是一般的api是没有问题的，再次谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: WenchangMai<mailto:notifications@github.com>
发送时间: 2020年5月7日 16:31
收件人: maiwenchang/ArtPlayer<mailto:ArtPlayer@noreply.github.com>
抄送: 雅心姐<mailto:alaireileen@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [maiwenchang/ArtPlayer] 播放会有卡顿现象，使用exo内核 (#37)


现在在重构Kotlin版本，会暴露播放器内核，可以自行调整缓存策略

―

**Comment by maiwenchang** [comment]
感谢你的支持，相互学习，共同进步🙏
