### ISSUE TITLE
怎么没有公开监听方法

### ISSUE THREAD

**Issue by luhuanxml** [maiwenchang/ArtPlayer#38]

**Comment by luhuanxml** [comment]
我用来做成上下滑动类似抖音样式刷小视频。虽然可以释放和开始视频，但是我还是想有开始播放和停止播放的监听回调。

**Comment by luhuanxml** [comment]
还有封面设置后，没有在视频显示前显示出来

**Comment by maiwenchang** [comment]
播放状态有监听方法的，可以参考说明文档，https://github.com/maiwenchang/ArtPlayer/wiki/%E6%92%AD%E6%94%BE%E5%86%85%E6%A0%B8#%E6%92%AD%E6%94%BE%E7%8A%B6%E6%80%81%E7%9A%84%E7%9B%91%E5%90%AC

**Comment by maiwenchang** [comment]
> 我用来做成上下滑动类似抖音样式刷小视频。虽然可以释放和开始视频，但是我还是想有开始播放和停止播放的监听回调。

文档还在完善中

**Comment by maiwenchang** [comment]
> 还有封面设置后，没有在视频显示前显示出来

可以看下你的版本和设置方法吗？

**Comment by luhuanxml** [comment]
不好意思，最近忙，没关注到 ，下面是我的代码
implementation 'org.salient.artvideoplayer:artplayer-core:1.0.0'

               videoPlayer.cover.setImageUrlWithoutPlace(videoBean.coverPhoto)
                val mediaPlayer = SystemMediaPlayer()
                videoPlayer.mediaPlayer = mediaPlayer.apply {
                    //抖音视频被下架的时候会出问题 进行播放异常处理
                    try {
                        setDataSource(context, Uri.parse(videoBean.playUrl))
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                    setLooping(true)
                }

                players.add(mediaPlayer)
                if (position == index) {
                    videoPlayer.prepare()
                    videoPlayer.stop()
                    videoPlayer.start()
                }

               fun ImageView.setImageUrlWithoutPlace(imageUrl: String?) {
                        RequestOptions().also {
                                it.diskCacheStrategy(DiskCacheStrategy.RESOURCE)
                       }.let {
                              Glide.with(appContent).load(imageUrl).apply(it).into(this)
                       }
                }

**Comment by maiwenchang** [comment]
VideoView如果放在列表里，可能要考虑item的复用问题。cover在播放开始的时候会被隐藏，建议在需要显示调用一下setVisibility()

**Comment by luhuanxml** [comment]
谢谢，原来如此
