### ISSUE TITLE
播放过程中VideoView的onMeasure会一直被回调

### ISSUE THREAD

**Issue by mikaelzero** [maiwenchang/ArtPlayer#4]
播放过程中VideoView的onMeasure会一直被回调

**Comment by ironman6121** [comment]
> 播放过程中VideoView的onMeasure会一直被回调

还会出现这个问题吗

**Comment by mikaelzero** [comment]
测试了下  是因为父布局的原因 子view更改大小后  会requestLayout父view的  所以属于正常现象

**Comment by ironman6121** [comment]
> 测试了下 是因为父布局的原因 子view更改大小后 会requestLayout父view的 所以属于正常现象

ok
