### ISSUE TITLE
进度条进度怎么做

### ISSUE THREAD

**Issue by Idumuzhou** [maiwenchang/ArtPlayer#46]
AbsControlPanel这个没有看到

**Comment by maiwenchang** [comment]
https://github.com/maiwenchang/ArtPlayer/wiki/2-%E6%92%AD%E6%94%BE%E5%86%85%E6%A0%B8#%E6%92%AD%E6%94%BE%E8%BF%9B%E5%BA%A6%E7%9B%91%E5%90%AC

**Comment by maiwenchang** [comment]
现在不提供视图了，进度条可以监听播放进度自行实现
