### ISSUE TITLE
透明的activity全屏会出现问题

### ISSUE THREAD

**Issue by mikaelzero** [maiwenchang/ArtPlayer#6]
会出现位置错乱

**Comment by maiwenchang** [comment]
刚试了一下，透明Activity位置并没有位置错乱，但是发现了其他的问题，比如全屏的时候会调用上一个Activity的onDestory，也是莫名其妙

**Comment by maiwenchang** [comment]
> 会出现位置错乱

可以麻烦你提供一下截图嘛？我也想研究下透明Activity下是个什么情况

**Comment by mikaelzero** [comment]
位置错乱应该是我自己的问题
不过有个问题是  全屏视频的view会被重新创建 然后覆盖
![tim 20181108171741](https://user-images.githubusercontent.com/6696343/48189068-3769dc80-e37a-11e8-9e06-3eb199afdfc8.gif)
而且不知道为什么还强制把我的屏幕转成横屏不转回来了

下面是我activity的配置
```
android:configChanges="orientation|screenSize|keyboardHidden"          

android:theme="@style/Transparent"
```

```
    <style name="Transparent" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground" >@color/transparent</item>
        <item name="android:windowIsTranslucent">true</item>
    </style>
```

**Comment by maiwenchang** [comment]
> 位置错乱应该是我自己的问题
> 不过有个问题是 全屏视频的view会被重新创建 然后覆盖
> ![tim 20181108171741](https://user-images.githubusercontent.com/6696343/48189068-3769dc80-e37a-11e8-9e06-3eb199afdfc8.gif)
> 而且不知道为什么还强制把我的屏幕转成横屏不转回来了
> 
> 下面是我activity的配置
> 
> ```
> android:configChanges="orientation|screenSize|keyboardHidden"          
> 
> android:theme="@style/Transparent"
> ```
> ```
>     <style name="Transparent" parent="Theme.AppCompat.Light.NoActionBar">
>         <item name="android:windowBackground" >@color/transparent</item>
>         <item name="android:windowIsTranslucent">true</item>
>     </style>
> ```

这确实是没有考虑到的地方，被重新创建应该是`MediaPlayerManager.instance().releasePlayerAndView(this);`被错误调用了。
我通过测试，发现启动全屏的时候，这个透明Activity的上一个Activity的OnDestroy被触发了。你可以在`MediaPlayerManager.instance().releasePlayerAndView(this)；`的地方打个断点，然后开启看看哪个地方误触了这个方法。

**Comment by maiwenchang** [comment]
> 位置错乱应该是我自己的问题
> 不过有个问题是 全屏视频的view会被重新创建 然后覆盖
> ![tim 20181108171741](https://user-images.githubusercontent.com/6696343/48189068-3769dc80-e37a-11e8-9e06-3eb199afdfc8.gif)
> 而且不知道为什么还强制把我的屏幕转成横屏不转回来了
> 
> 下面是我activity的配置
> 
> ```
> android:configChanges="orientation|screenSize|keyboardHidden"          
> 
> android:theme="@style/Transparent"
> ```
> ```
>     <style name="Transparent" parent="Theme.AppCompat.Light.NoActionBar">
>         <item name="android:windowBackground" >@color/transparent</item>
>         <item name="android:windowIsTranslucent">true</item>
>     </style>
> ```
手机的SDK是什么版本，我在配置透明Activity的时候就遇到坑了，一全屏就crash，你可以参考下这篇文章的：
https://zhuanlan.zhihu.com/p/32190223

**Comment by mikaelzero** [comment]
确实是会出现这个错误  我暂时的解决方案是不手动全屏

**Comment by maiwenchang** [comment]
> 确实是会出现这个错误 我暂时的解决方案是不手动全屏

嗯嗯，加油么么哒，我也会尝试解决这个坑
